### ISSUE TITLE
Detecting Rotated Left, Right & Upsidedown

### ISSUE THREAD

**Issue by nuzly** [Sicos1977/PageOrientationEngine#2]
I've made some naive changes to this function which appear to be working for the 4x 90' rotations.
I also had to adjust the counter condition used below to get it to work at all. The original setting was <5. 
` if (counter < 2) continue;
                            found = pageIterator.TryGetBoundingBox(PageIteratorLevel.TextLine, out rect);
                            break;`

`    public DocumentInspectorPageOrientation DetectPageOrientation(Bitmap bitmap)
        {
            if (bitmap == null)
                throw new NullReferenceException("The bitmap parameter is not set");

            if (bitmap.PixelFormat == PixelFormat.Format1bppIndexed)
                bitmap = BitmapUtils.CopyToBpp(bitmap, 8);

            using (var engine = new TesseractEngine(TesseractDataPath, TesseractLanguage))
            {
                var rect = new Rect();

                using (var image = PixConverter.ToPix(bitmap))
                using (var page = engine.Process(image, PageSegMode.AutoOsd))
                {
                    var pageIterator = page.AnalyseLayout();
                    pageIterator.Begin();

                    while (pageIterator.Next(PageIteratorLevel.Block))
                    {
                        var found = false;

                        
                        while (pageIterator.Next(PageIteratorLevel.Para))
                        {
                            var counter = 0;

                            while (pageIterator.Next(PageIteratorLevel.TextLine, PageIteratorLevel.Word))
                                counter++;

                            if (counter < 2) continue;
                            found = pageIterator.TryGetBoundingBox(PageIteratorLevel.TextLine, out rect);
                            break;
                        }
                        

                        var croppedRect = new Rectangle(rect.X1, rect.Y1, rect.Width, rect.Height);
                        if (rect.Height == 0)
                            return DocumentInspectorPageOrientation.Undetectable;

                        var croppedImage = found
                            ? bitmap.Clone(croppedRect, bitmap.PixelFormat)
                            : bitmap.Clone() as Bitmap;

                        // The OCR confidence on the first run
                        float firstMeanConfedence;

                        // The OCR confidence on the second run
                        float secondMeanConfedence;

                        // The OCR confidence on the second run
                        float thirdMeanConfedence;

                        // The OCR confidence on the second run
                        float fourthMeanConfedence;

                        using (var engineCroppedImage = new TesseractEngine(TesseractDataPath, TesseractLanguage))
                        {
                            using (var imageNormal = PixConverter.ToPix(croppedImage))
                            using (var pageNormal = engineCroppedImage.Process(imageNormal))
                                firstMeanConfedence = pageNormal.GetMeanConfidence();

                            if (firstMeanConfedence > 0.75)
                                return DocumentInspectorPageOrientation.PageCorrect;
                            
                            // Rotate image 90 degrees
                            croppedImage.RotateFlip(RotateFlipType.Rotate90FlipNone);
                            //croppedImage.Save(@"d:\\Crop area flipped.tif", System.Drawing.Imaging.ImageFormat.Tiff);

                            using (var imageRotated90 = PixConverter.ToPix(croppedImage))
                            using (var pageRotated90 = engineCroppedImage.Process(imageRotated90))
                                secondMeanConfedence = pageRotated90.GetMeanConfidence();
                            if (secondMeanConfedence > 0.75)
                                return DocumentInspectorPageOrientation.PageRotatedLeft;

                            // Rotate image 180 degrees
                            croppedImage.RotateFlip(RotateFlipType.Rotate90FlipNone);
                            //croppedImage.Save(@"d:\\Crop area flipped.tif", System.Drawing.Imaging.ImageFormat.Tiff);

                            using (var imageRotated180 = PixConverter.ToPix(croppedImage))
                            using (var pageRotated180 = engineCroppedImage.Process(imageRotated180))
                                thirdMeanConfedence = pageRotated180.GetMeanConfidence();
                            if (thirdMeanConfedence > 0.65)
                                return DocumentInspectorPageOrientation.PageUpsideDown;

                          

                             // Rotate image 270 degrees
                             croppedImage.RotateFlip(RotateFlipType.Rotate90FlipNone);
                             //croppedImage.Save(@"d:\\Crop area flipped.tif", System.Drawing.Imaging.ImageFormat.Tiff);

                             using (var imageRotated270 = PixConverter.ToPix(croppedImage))
                             using (var pageRotated270 = engineCroppedImage.Process(imageRotated270))
                                 fourthMeanConfedence = pageRotated270.GetMeanConfidence();
                             if (fourthMeanConfedence > 0.65)
                                 return DocumentInspectorPageOrientation.PageRotatedRight;

                       

                        }

                        croppedImage.Dispose();
                        float[] vals = new float[4] { firstMeanConfedence, secondMeanConfedence, thirdMeanConfedence, fourthMeanConfedence };

                        int hpos = -1;
                        float hval = 0;
                        for (int i = 0; i < vals.Length; i++) {
                            if (vals[i] > hval) { hpos = i; hval = vals[i]; }
                        }
                        if (hpos == 0) { return DocumentInspectorPageOrientation.PageCorrect; }
                        if (hpos == 1) { return DocumentInspectorPageOrientation.PageRotatedLeft; }
                        if (hpos == 2) { return DocumentInspectorPageOrientation.PageUpsideDown; }
                        if (hpos == 3) { return DocumentInspectorPageOrientation.PageRotatedRight; }

                        return DocumentInspectorPageOrientation.Undetectable;

                        /*

                        if (firstMeanConfedence > 0.40 && secondMeanConfedence > 0.40)
                            return firstMeanConfedence >= secondMeanConfedence
                                ? DocumentInspectorPageOrientation.PageCorrect
                                : DocumentInspectorPageOrientation.PageRotatedLeft;
                          */      
                    }
                }
                return DocumentInspectorPageOrientation.Undetectable;
            }

        }`

**Comment by mbrucco** [comment]
it is not recognizing me a document that is clockwise rotate 90°...
